### PR TITLE
Updated to compile on Windows MinGW32

### PR DESCRIPTION
**Pull request by jtp10181**
I think I figure out the correct way to do this...

This should still compile with xcode on the Mac. I do not have a Mac to test though.
I updated the hid.c for mac and added hid_win.c for windows. Updated the hdiapi.h also to go with them. They are direct from the source without modification.

Added a Makefile for mingw, not sure if the other makefile is used for mac so I left it alone.

Converted usleep to not throw errors on mingw, should retain full compatibility with xcode on mac.

Note: I cant get it to play nice with my newer portals I have. But the rest of the program works as designed. I have a bunch of other patches coming.

### CODE REVIEW

**Comment by crstofer** [comment]
Can u share your compiled version for Windows? I try to compile and keep getting error message. PLEASE & Thanks !

**Comment by jtp10181** [comment]
You can use my fork from here:

https://github.com/jtp10181/SkyReader

+##################################################
+#  Makefile for MinGW32 on windows by jtp10181
+#  To compile run: mingw32-make -f Makefile.mingw
+##################################################

**Comment by crstofer** [comment]
Jeff , 
Thanks. I cant get it to compile.. can u share your compiled exe? If not, no worries ! 
I've installed mingw and run mingw32-make -f Makefile.mingw, starts to compile then error withg output.exe. "headache!"

**Comment by crstofer** [comment]
c:/mingw/bin/../lib/gcc/mingw32/4.7.2/../../../../mingw32/bin/ld.exe: cannot ope
n output file bin\editor.exe: No such file or directory
collect2.exe: error: ld returned 1 exit status
Makefile.mingw:16: recipe for target 'editor' failed
mingw32-make: *** [editor] Error 1

any advice ?

**Pull request merged**
