### PR TITLE
Linux support. Updated hid.c for for Win/Linux and modified hid_write…

### PR DESCRIPTION
**Pull request by capull0**
… to work with SkyReader

i symlinked now the Makefile.
In my Branch i'am using cmake, but to keep the pull request small i created it based on your master.

tested with all PS3 portals on linux and windows 10

### CODE REVIEW

**Comment by hegyak** [comment]
I tested this against my Trap Team portal (non-Xbox 360).  This fix did not work.  Skylander not found.  Nor were traps in the hole or on the platform detected/read.

However using a Swap Force portal (Non-Xbox 360) and that worked fine.  Reads Skylanders just fine.  Traps, are still not detected/read.

I will try and get some time to test the XBox 360 portals.

**Comment by capull0** [comment]
i tested it also with a Superchargers Portal, which also have a Trap hole. Skylanders are working. Traps not yet tested.

if you get a "Skylander not found" the communication is at least working, because until this point, there were successful requests. (R, A, S, C)
i created a fork from SkyReader. I called it SkyDumper, where i only implemented the possibility to backup/dump, restore and reset any skylanders.
https://github.com/capull0/SkyDumper

is fully based on SkyReader, but i changed the communication to wait for each request, until i get the proper response.

**Comment by capull0** [comment]
anyway, in the future i don't need a portal anymore. i developed something where my Raspberry Pi Zero is acting as Lego Dimensions, Disney Infinity or Skylanders Portal.
Problem was not to use the USB-Device from the Pi Zero for Wifi. I am using a ESP8266 now for Wifi to control the Zero over a web application.
working flawless :)

**Comment by cuthred** [comment]
Any chance you can/will share your solution to use Raspi 0 to get the data from Lego/DI/Skynalders?

**Pull request closed without merging**
